# Generated by Django 3.1.5 on 2024-02-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_iletisimmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iletisimmodel',
            options={'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişim'},
        ),
    ]
