# Generated by Django 3.1.5 on 2024-02-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240201_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorummodel',
            name='guncellenme_tarihi',
        ),
        migrations.AddField(
            model_name='yorummodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
